-----
# **Context**
-----

**WOW Superstore** sells different products like office supplies, furniture and appliances. For each order that is placed, the superstore keeps a record of various attributes related to the product, like state, city, category, subcategory and quantity.

**Let's display a welcome message from WOW Superstore.**

* We can use the print() function for this purpose.

In [2]:
message = "Hi! Welcome to WOW Superstore"
print(message)

Hi! Welcome to WOW Superstore

**The superstore has a stock of 100 phones. Recently, an order was placed for 20 phones. It has to be updated to add 10 more phones.**

In [3]:
order_int = 20
print("Initial Order", order_int)
order_update = order_int+ 10
print("Updated Order",order_update)

Initial Order 20
Updated Order 10

**The inventory has to be updated as per the updated order. We will have to subtract the quantity of phones in the updated order (order_upd) from the initial inventory count of 100.**

In [4]:
inventory_initial = 100
print("Initial Inventory",inventory_initial)
inventory_initial = inventory_initial - order_update

print("Current inventory",inventory_initial )

Initial Inventory 100
Current inventory 90

**The cost of each phone is $150.50. Let's compute the total amount for the updated order (order_upd).**

In [5]:
quantity = 30
unit_price = 150
total_amount = quantity *unit_price
print(total_amount)

4500

**For the upcoming Black Friday sale, the superstore is providing a discount of 20% on phones and 10% on chairs, but there is no discount on any other product.**

**For a given product, let's display a message that informs a customer about how much discount they will get on their order.**

In [9]:
product = input('Enter the Product')
if product == 'phone':
   print("You will receive 20% offer for this phone product")
elif product == 'chair':
   print("You will receive 10% offer for this  chair product")
else :
   print(" No offer for this  product")

KeyboardInterrupt: Interrupted by user

| Order ID | Category | Sub-Category | Quantity | Unit Price |
| --- | --- | --- | --- | --- |
| WOWORD001 | Office Supplies | Binders | 3 | 10.20 |
| WOWORD002 | Technology | Phones | 30 | 150.50 |
| WOWORD003 | Office Supplies | Paper | 50 | 4.50 |
| WOWORD004 | Furniture | Chairs | 5 | 30.75 |
| WOWORD005 | Office Supplies | Binders | 2 | 10.20 |

In [12]:
order_id_list =["WOWORD001","WOWORD002","WOWORD003","WOWORD004","WOWORD005"]
print('order_id_list',order_id_list)
category_list = ['Office Supplies', 'Technology', 'Office Supplies', 'Furniture', 'Office Supplies']
print('Category_list',category_list)
sub_category_list = ['Binders', 'Phones', 'Paper', 'Chairs', 'Binders']
print('SubCategoryList',sub_category_list)
quantity_list =[3, 30, 50, 5, 2]
print('Qunatity_list',quantity_list)
unit_price_list = [10.20, 150.50, 4.50, 30.75, 10.20]
print('Unit_Price_list',unit_price_list)

order_id_list ['WOWORD001', 'WOWORD002', 'WOWORD003', 'WOWORD004', 'WOWORD005']
Category_list ['Office Supplies', 'Technology', 'Office Supplies', 'Furniture', 'Office Supplies']
SubCategoryList ['Binders', 'Phones', 'Paper', 'Chairs', 'Binders']
Qunatity_list [3, 30, 50, 5, 2]
Unit_Price_list [10.2, 150.5, 4.5, 30.75, 10.2]

* If we want to analyze this data, we will have to work with multiple lists.
* It will not be feasible to apply different operations on multiple lists, especially if the number of attributes increases.
* So, it is clear we need a more efficient way of handling the data simultaneously at the attribute and record levels.
* In Python, we can do this with pandas dataframe.
* pandas is a powerful, easy-to-use, open-source Python library used for data analysis and manipulation.
* It is very useful when working with tabular data.
* Python has many other libraries which are useful for different tasks.
* We can import these libraries into a Jupyter notebook to access and use the functionalities of these libraries.

In [15]:
from re import sub
import pandas as pd
superstore_data  = pd.DataFrame()
superstore_data['OrderId'] = order_id_list
superstore_data['Category'] = category_list
superstore_data['SubCategory'] = sub_category_list
superstore_data['Quantity'] = quantity
superstore_data['UnitPriceList'] = unit_price_list
superstore_data['TotalAmount'] = superstore_data['Quantity'] * superstore_data['UnitPriceList']
superstore_data

,OrderId,Category,SubCategory,Quantity,UnitPriceList,TotalAmount
0,WOWORD001,Office Supplies,Binders,30,10.20,306.0
1,WOWORD002,Technology,Phones,30,150.50,4515.0
2,WOWORD003,Office Supplies,Paper,30,4.50,135.0
3,WOWORD004,Furniture,Chairs,30,30.75,922.5
4,WOWORD005,Office Supplies,Binders,30,10.20,306.0

**The superstore is currently not shipping office supplies due to COVID restrictions.**

**We have to print an appropriate message for the customer depending upon the category of the product ordered.**

In [17]:
for i in superstore_data['Category']:
  print('Product Ordered',i)
  if i == 'Office Supplies':
     print('Sorry!, Currently the product cannot be shipped')
  else :
    print('Your order will be shipped at your earliest')

Product Ordered Office Supplies
Sorry!, Currently the product cannot be shipped
Product Ordered Technology
Your order will be shipped at your earliest
Product Ordered Office Supplies
Sorry!, Currently the product cannot be shipped
Product Ordered Furniture
Your order will be shipped at your earliest
Product Ordered Office Supplies
Sorry!, Currently the product cannot be shipped

In [33]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [53]:




# Verify files

%cd /content
!ls /content/drive/MyDrive/AIMLGitHub/

data = pd.read_csv('/content/drive/MyDrive/AIMLGitHub/WOWSuperstore.csv')

/content
WOWSuperstore.csv

In [56]:

data.tail()

,Order ID,Ship Mode,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
1945,WOWID1946,Standard Class,Corporate,Philadelphia,Pennsylvania,East,Office Supplies,Paper,3.4240,1,0.20,1.0700
1946,WOWID1947,Standard Class,Corporate,Philadelphia,Pennsylvania,East,Technology,Accessories,151.2000,3,0.20,32.1300
1947,WOWID1948,First Class,Home Office,Houston,Texas,Central,Office Supplies,Paper,65.5840,2,0.20,23.7742
1948,WOWID1949,First Class,Home Office,Houston,Texas,Central,Furniture,Bookcases,383.4656,4,0.32,-67.6704
1949,WOWID1950,Standard Class,Consumer,Houston,Texas,Central,Office Supplies,Envelopes,99.5680,2,0.20,33.6042

In [57]:
data.head()

,Order ID,Ship Mode,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,WOWID0001,Standard Class,Consumer,Seattle,Washington,West,Office Supplies,Binders,407.976,3,0.2,132.5922
1,WOWID0002,Standard Class,Home Office,Fort Worth,Texas,Central,Office Supplies,Appliances,68.810,5,0.8,-123.8580
2,WOWID0003,Standard Class,Home Office,Fort Worth,Texas,Central,Office Supplies,Binders,2.544,3,0.8,-3.8160
3,WOWID0004,Standard Class,Consumer,Philadelphia,Pennsylvania,East,Furniture,Bookcases,3083.430,7,0.5,-1665.0522
4,WOWID0005,Standard Class,Consumer,Philadelphia,Pennsylvania,East,Office Supplies,Binders,9.618,2,0.7,-7.0532